
import { Discipline, SpotCategory, Difficulty, SkillState, Spot, Skill, VerificationStatus, Collectible, CollectibleType, Rarity, ExtendedSession, Challenge, Mentor, MentorBadge, DailyNote, SpotStatus, Badge, BadgeTier, SpotPrivacy } from './types';

export const RETRO_AVATARS = [
  'https://api.dicebear.com/7.x/pixel-art/svg?seed=SkaterBoy',
  'https://api.dicebear.com/7.x/pixel-art/svg?seed=RetroContra',
  'https://api.dicebear.com/7.x/pixel-art/svg?seed=LegoMan',
  'https://api.dicebear.com/7.x/pixel-art/svg?seed=ArcadeQueen'
];

export const STATE_IMAGES: Record<string, string> = {
  "Maharashtra": "https://images.unsplash.com/photo-1562920618-3e26f9ee00ad?w=800",
  "Karnataka": "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800",
  "Delhi": "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800",
  "Goa": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800",
  "Kerala": "https://images.unsplash.com/photo-1593549423923-19a6902b6878?w=800",
  "Tamil Nadu": "https://images.unsplash.com/photo-1582510003544-524378994569?w=800",
  "Himachal Pradesh": "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800"
};

// --- XP SYSTEM ---
export const XP_SOURCES = {
  SESSION_COMPLETE: 50,
  SESSION_PLANNED: 75,
  STREAK_BONUS: 20, // Per day, capped at 3
  CHALLENGE_COMPLETE: 150, // Base
  SKILL_LANDED: 80,
  SKILL_MASTERED: 200,
  SPOT_CONTRIBUTION: 40,
  MENTOR_SESSION: 120,
  LEARNER_SESSION: 80
};

export const BADGE_DATABASE: Badge[] = [
  { id: 'badge_rookie_push', name: 'First Push', description: 'Began the journey.', tier: BadgeTier.ROOKIE, icon: 'Footprints', conditionDescription: 'Reach Level 2' },
  { id: 'badge_rookie_spotter', name: 'Spotter', description: 'Eyes on the street.', tier: BadgeTier.ROOKIE, icon: 'MapPin', conditionDescription: 'Find or Verify 1 Spot' },
  { id: 'badge_initiate_dedicated', name: 'Dedicated', description: 'Consistency is key.', tier: BadgeTier.INITIATE, icon: 'Zap', conditionDescription: 'Maintain a 3-day streak' },
  { id: 'badge_initiate_local', name: 'The Local', description: 'Part of the furniture.', tier: BadgeTier.INITIATE, icon: 'Home', conditionDescription: 'Complete 10 Sessions' },
  { id: 'badge_skilled_scholar', name: 'Scholar', description: 'Student of the game.', tier: BadgeTier.SKILLED, icon: 'BookOpen', conditionDescription: 'Master 5 Skills' },
  { id: 'badge_skilled_challenger', name: 'Contender', description: 'Stepping up.', tier: BadgeTier.SKILLED, icon: 'Swords', conditionDescription: 'Complete 5 Challenges' },
  { id: 'badge_veteran_guardian', name: 'Guardian', description: 'Protector of the scene.', tier: BadgeTier.VETERAN, icon: 'Shield', conditionDescription: 'Verify 5 Spots & Reach Level 15' },
  { id: 'badge_veteran_mentor', name: 'Sensei', description: 'Passing the torch.', tier: BadgeTier.VETERAN, icon: 'Users', conditionDescription: 'Host a Mentorship Session' },
  { id: 'badge_legend_legacy', name: 'Legacy', description: 'Your name echoes.', tier: BadgeTier.LEGEND, icon: 'Crown', conditionDescription: 'Reach Level 50' }
];

// --- MASTER SPOT DATABASE (FROM CSV) ---
export const MOCK_SPOTS: Spot[] = [
  // SKATEPARKS & STREET
  {
    id: 'assam-nfr-skatepark',
    name: 'NFR Skatepark (Maligaon)',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.INTERMEDIATE,
    state: 'Assam',
    surface: 'Concrete',
    location: { lat: 26.1600, lng: 91.7000, address: 'Guwahati, Assam' },
    notes: 'Railways community skatepark (NFR).',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1520156584189-1e4529f8c9b3?w=800'],
    sessions: []
  },
  {
    id: 'noida-pump-track',
    name: 'Noida Pump Track',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.INTERMEDIATE,
    state: 'Delhi',
    surface: 'Concrete',
    location: { lat: 28.5355, lng: 77.3910, address: 'Noida, Delhi NCR' },
    notes: 'Pumptrack and skate areas. 100Ramps build.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.6,
    images: ['https://images.unsplash.com/photo-1572505543666-4836696db307?w=800'],
    sessions: []
  },
  {
    id: 'goa-anjuna-bowl',
    name: 'Anjuna Bowl',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.ADVANCED,
    state: 'Goa',
    surface: 'Concrete',
    location: { lat: 15.5736, lng: 73.7406, address: 'Anjuna, Goa' },
    notes: 'Concrete bowl & local community by the beach.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.8,
    images: ['https://images.unsplash.com/photo-1564982752979-3f7bc974d29a?w=800'],
    sessions: []
  },
  {
    id: 'goa-miramar-park',
    name: 'Miramar Skatepark',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.BEGINNER,
    state: 'Goa',
    surface: 'Concrete',
    location: { lat: 15.4732, lng: 73.8079, address: 'Miramar, Goa' },
    notes: 'Public skate area near Cirrus.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.CROWDED,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.2,
    images: ['https://images.unsplash.com/photo-1536520002442-39764a41e987?w=800'],
    sessions: []
  },
  {
    id: 'ahmedabad-riverfront',
    name: 'Sabarmati Riverfront',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.INTERMEDIATE,
    state: 'Gujarat',
    surface: 'Concrete',
    location: { lat: 23.0225, lng: 72.5714, address: 'Ahmedabad, Gujarat' },
    notes: 'Riverfront skate facilities by 100Ramps.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.7,
    images: ['https://images.unsplash.com/photo-1520156584189-1e4529f8c9b3?w=800'],
    sessions: []
  },
  {
    id: 'vadodara-skatepark',
    name: 'Vadodara Skatepark',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.INTERMEDIATE,
    state: 'Gujarat',
    surface: 'Concrete',
    location: { lat: 22.3072, lng: 73.1812, address: 'Vadodara, Gujarat' },
    notes: 'Community skatepark.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.3,
    images: [],
    sessions: []
  },
  {
    id: 'chandigarh-sector-17',
    name: 'Sector 17 Plaza',
    type: Discipline.SKATE,
    category: SpotCategory.STREET,
    difficulty: Difficulty.BEGINNER,
    state: 'Haryana',
    surface: 'Tiles/Concrete',
    location: { lat: 30.7333, lng: 76.7794, address: 'Chandigarh' },
    notes: 'Public plazas and civic spaces. Good flatground.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.CROWDED,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.0,
    images: [],
    sessions: []
  },
  {
    id: 'bengaluru-holystoked',
    name: 'The Cave (Holystoked)',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.ADVANCED,
    state: 'Karnataka',
    surface: 'Concrete/Wood',
    location: { lat: 12.9352, lng: 77.6245, address: 'Bengaluru, Karnataka' },
    notes: 'Legendary DIY spot turned community hub. Tight transitions.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.9,
    images: ['https://images.unsplash.com/photo-1564982752979-3f7bc974d29a?w=800'],
    sessions: []
  },
  {
    id: 'bengaluru-play-arena',
    name: 'Play Arena Skatepark',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.INTERMEDIATE,
    state: 'Karnataka',
    surface: 'Concrete',
    location: { lat: 12.8426, lng: 77.6648, address: 'Sarjapur, Bengaluru' },
    notes: 'Commercial skatepark with bowl and street section.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.5,
    images: [],
    sessions: []
  },
  {
    id: 'kerala-kovalam-park',
    name: 'Kovalam Skatepark',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.INTERMEDIATE,
    state: 'Kerala',
    surface: 'Concrete',
    location: { lat: 8.3833, lng: 76.9714, address: 'Kovalam, Kerala' },
    notes: 'Community beachside skatepark. Surf & Skate vibe.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.WET,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.7,
    images: ['https://images.unsplash.com/photo-1536520002442-39764a41e987?w=800'],
    sessions: []
  },
  {
    id: 'gwalior-gsc',
    name: 'GSC Skatepark',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.INTERMEDIATE,
    state: 'Madhya Pradesh',
    surface: 'Concrete',
    location: { lat: 26.1910, lng: 78.1700, address: 'Gwalior, MP' },
    notes: 'Gwalior Sickness Centre. Local hub.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.6,
    images: [],
    sessions: []
  },
  {
    id: 'janwaar-castle',
    name: 'Janwaar Castle',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.INTERMEDIATE,
    state: 'Madhya Pradesh',
    surface: 'Concrete',
    location: { lat: 24.3300, lng: 80.2700, address: 'Panna, MP' },
    notes: 'Rural community skatepark. The first of its kind.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 5.0,
    images: ['https://images.unsplash.com/photo-1473445730015-841f29a9490b?w=800'],
    sessions: []
  },
  {
    id: 'mumbai-carter',
    name: 'Carter Road Skatepark',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.INTERMEDIATE,
    state: 'Maharashtra',
    surface: 'Concrete',
    location: { lat: 19.0607, lng: 72.8227, address: 'Bandra, Mumbai' },
    notes: 'Public promenade skatepark. The OG Mumbai spot.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.CROWDED,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.8,
    images: ['https://images.unsplash.com/photo-1572505543666-4836696db307?w=800'],
    sessions: []
  },
  {
    id: 'navi-mumbai-nerul',
    name: 'Nerul Skatepark',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.BEGINNER,
    state: 'Maharashtra',
    surface: 'Concrete',
    location: { lat: 19.0365, lng: 73.0186, address: 'Nerul, Navi Mumbai' },
    notes: 'Concrete plaza with modules inside a park.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.1,
    images: [],
    sessions: []
  },
  {
    id: 'pune-sahakarnagar',
    name: 'Sahakarnagar Skatepark',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.INTERMEDIATE,
    state: 'Maharashtra',
    surface: 'Concrete',
    location: { lat: 18.4870, lng: 73.8470, address: 'Pune, Maharashtra' },
    notes: 'Municipal skatepark. Baba Saheb Ambedkar park.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.4,
    images: [],
    sessions: []
  },
  {
    id: 'delhi-cp-ledges',
    name: 'Connaught Place',
    type: Discipline.SKATE,
    category: SpotCategory.STREET,
    difficulty: Difficulty.BEGINNER,
    state: 'Delhi',
    surface: 'Marble/Tiles',
    location: { lat: 28.6315, lng: 77.2167, address: 'CP Inner Circle, Delhi' },
    notes: 'Classic plaza. Marble ledges. Bust potential high.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.MAINTENANCE,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.3,
    images: [],
    sessions: []
  },
  {
    id: 'rajasthan-desert-dolphin',
    name: 'Desert Dolphin Skatepark',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.ADVANCED,
    state: 'Rajasthan',
    surface: 'Concrete',
    location: { lat: 26.2100, lng: 73.3200, address: 'Khempur, Rajasthan' },
    notes: 'Large transition park. Film location.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 5.0,
    images: [],
    sessions: []
  },
  {
    id: 'chennai-madras-wheelers',
    name: 'Madras Wheelers',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.INTERMEDIATE,
    state: 'Tamil Nadu',
    surface: 'Concrete',
    location: { lat: 13.0827, lng: 80.2707, address: 'Chennai, TN' },
    notes: 'Community skate facility.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.4,
    images: [],
    sessions: []
  },
  {
    id: 'hyderabad-wallride',
    name: 'WallRide Park',
    type: Discipline.SKATE,
    category: SpotCategory.PARK,
    difficulty: Difficulty.ADVANCED,
    state: 'Telangana',
    surface: 'Asphalt/Concrete',
    location: { lat: 17.3000, lng: 78.4250, address: 'Peerancheru, Hyderabad' },
    notes: 'Pump track + skatepark combo.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.8,
    images: [],
    sessions: []
  },
  
  // DOWNHILL SPOTS
  {
    id: 'spot-dh-lonavala-khandala',
    name: 'Khandala Ghat',
    type: Discipline.DOWNHILL,
    category: SpotCategory.DOWNHILL,
    difficulty: Difficulty.ADVANCED,
    state: 'Maharashtra',
    surface: 'Asphalt',
    location: { lat: 18.7509, lng: 73.3897, address: 'Lonavala, Maharashtra' },
    notes: 'Classic ghats for longboard runs. Traffic warning.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.9,
    images: ['https://images.unsplash.com/photo-1465449767222-6b943232bb39?w=800'],
    sessions: []
  },
  {
    id: 'dh-nandi-hills',
    name: 'Nandi Hills',
    type: Discipline.DOWNHILL,
    category: SpotCategory.DOWNHILL,
    difficulty: Difficulty.ADVANCED,
    state: 'Karnataka',
    surface: 'Asphalt',
    location: { lat: 13.3702, lng: 77.6835, address: 'Bengaluru Outskirts' },
    notes: 'Famous downhill run. Steep hairpins.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.8,
    images: [],
    sessions: []
  },
  {
    id: 'pune-hills',
    name: 'Lavasa Downhill',
    type: Discipline.DOWNHILL,
    category: SpotCategory.DOWNHILL,
    difficulty: Difficulty.PRO,
    state: 'Maharashtra',
    surface: 'Asphalt',
    location: { lat: 18.4000, lng: 73.5000, address: 'Lavasa Road' },
    notes: 'World class hairpin bends. Serious speed capability.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 5.0,
    images: ['https://images.unsplash.com/photo-1517173950239-2c70d49942d9?w=800'],
    sessions: []
  },
  {
    id: 'dh-ponmudi',
    name: 'Ponmudi Ghats',
    type: Discipline.DOWNHILL,
    category: SpotCategory.DOWNHILL,
    difficulty: Difficulty.ADVANCED,
    state: 'Kerala',
    surface: 'Asphalt',
    location: { lat: 8.7609, lng: 77.1107, address: 'Trivandrum, Kerala' },
    notes: 'Technical ghat section.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.6,
    images: [],
    sessions: []
  },
  {
    id: 'dh-yercaud',
    name: 'Yercaud Ghat',
    type: Discipline.DOWNHILL,
    category: SpotCategory.DOWNHILL,
    difficulty: Difficulty.ADVANCED,
    state: 'Tamil Nadu',
    surface: 'Asphalt',
    location: { lat: 11.7753, lng: 78.2095, address: 'Salem, TN' },
    notes: 'Smooth descent with 20 hairpins.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.7,
    images: [],
    sessions: []
  },
  {
    id: 'dh-mussoorie',
    name: 'Mussoorie Bypass',
    type: Discipline.DOWNHILL,
    category: SpotCategory.DOWNHILL,
    difficulty: Difficulty.INTERMEDIATE,
    state: 'Uttarakhand',
    surface: 'Asphalt',
    location: { lat: 30.4599, lng: 78.0664, address: 'Mussoorie' },
    notes: 'Scenic mountain roads.',
    isVerified: false,
    verificationStatus: VerificationStatus.PENDING,
    status: SpotStatus.DRY,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.2,
    images: [],
    sessions: []
  },
  {
    id: 'dh-shillong-cherra',
    name: 'Shillong-Cherra Road',
    type: Discipline.DOWNHILL,
    category: SpotCategory.DOWNHILL,
    difficulty: Difficulty.INTERMEDIATE,
    state: 'Meghalaya',
    surface: 'Asphalt',
    location: { lat: 25.2755, lng: 91.7326, address: 'Cherrapunji, Meghalaya' },
    notes: 'Cloudy, misty runs. Check visibility.',
    isVerified: true,
    verificationStatus: VerificationStatus.VERIFIED,
    status: SpotStatus.WET,
    privacy: SpotPrivacy.PUBLIC,
    rating: 4.9,
    images: [],
    sessions: []
  }
];

export const MOCK_CHALLENGES: Challenge[] = [
  {
    id: 'battle-carter-kickflip',
    spotId: 'mumbai-carter',
    creatorId: 'u-arjun',
    creatorName: 'Arjun S.',
    title: 'Carter Road Kickflip',
    description: 'Kickflip the gap over the planter. Clean landing required.',
    difficulty: Difficulty.INTERMEDIATE,
    xpReward: 300,
    completions: 14
  },
  {
    id: 'battle-khandala-tuck',
    spotId: 'spot-dh-lonavala-khandala',
    creatorId: 'u-vikram',
    creatorName: 'Vikram D.',
    title: 'Ghat Tuck Endurance',
    description: 'Hold a perfect aerodynamic tuck for the entire 1km straight section.',
    difficulty: Difficulty.ADVANCED,
    xpReward: 500,
    completions: 3
  },
  {
    id: 'battle-holystoked-line',
    spotId: 'bengaluru-holystoked',
    creatorId: 'u-sarah',
    creatorName: 'Sarah M.',
    title: 'Holy Transfer Line',
    description: 'Drop in, pump the hump, and frontside air over the hip.',
    difficulty: Difficulty.ADVANCED,
    xpReward: 400,
    completions: 8
  }
];

export const MOCK_SESSIONS: ExtendedSession[] = [
  {
    id: 'sess-1',
    userId: 'u-arjun',
    userName: 'Arjun S.',
    title: 'Sunday Morning Shred',
    date: '2025-05-20',
    time: '07:00',
    spotId: 'mumbai-carter',
    spotName: 'Carter Road Skatepark',
    spotType: Discipline.SKATE,
    participants: ['u-arjun']
  }
];

export const MOCK_MENTORS: Mentor[] = [
  {
    id: 'm-1',
    userId: 'u-arjun',
    name: 'Arjun S.',
    avatar: 'https://api.dicebear.com/7.x/pixel-art/svg?seed=Arjun',
    disciplines: [Discipline.SKATE],
    rate: 800,
    bio: 'Specializing in technical street and ledge work.',
    rating: 4.9,
    reviewCount: 22,
    earnings: 15000,
    studentsTrained: 12,
    badges: [MentorBadge.CERTIFIED, MentorBadge.EXPERT],
    stats: { technical: 95, style: 85, teaching: 90 }
  },
  {
    id: 'm-2',
    userId: 'u-vikram',
    name: 'Vikram D.',
    avatar: 'https://api.dicebear.com/7.x/pixel-art/svg?seed=Vikram',
    disciplines: [Discipline.DOWNHILL],
    rate: 1200,
    bio: 'Speed control, sliding and safety gear expert.',
    rating: 5.0,
    reviewCount: 15,
    earnings: 18000,
    studentsTrained: 8,
    badges: [MentorBadge.CERTIFIED],
    stats: { technical: 90, style: 95, teaching: 85 }
  }
];

export const MOCK_NOTES: DailyNote[] = [
  {
    id: 'note-1',
    userId: 'u-system',
    date: new Date().toISOString().split('T')[0],
    text: 'Skate conditions in Mumbai are prime today. Humidity is low.',
    timestamp: new Date().toISOString()
  }
];

// --- EXTENDED SKILL LIBRARY (TECH TREE) ---
export const SKILL_LIBRARY: Skill[] = [
  // ... (Kept existing structure)
  { id: 'skate-ollie', name: 'Ollie', category: Discipline.SKATE, difficulty: Difficulty.BEGINNER, tier: 1, xpReward: 100, description: 'The foundation. Snap the tail, slide the foot.', tutorialUrl: 'ArLl1N35ZWs' },
  { id: 'skate-shuvit', name: 'Shuv-it', category: Discipline.SKATE, difficulty: Difficulty.BEGINNER, tier: 1, xpReward: 150, description: 'Spin board 180 without popping.', tutorialUrl: 'Oq9Y3i7_G_E' },
  { id: 'skate-manual', name: 'Manual', category: Discipline.SKATE, difficulty: Difficulty.BEGINNER, tier: 1, xpReward: 100, description: 'Balance on back wheels.', tutorialUrl: 'l9y_1_1' },
  { id: 'skate-fs180', name: 'FS 180', category: Discipline.SKATE, difficulty: Difficulty.BEGINNER, tier: 1, xpReward: 150, description: 'Rotate body and board 180 frontside.', tutorialUrl: 'C5fLg3W7s80', prerequisiteId: 'skate-ollie' },
  { id: 'skate-bs180', name: 'BS 180', category: Discipline.SKATE, difficulty: Difficulty.BEGINNER, tier: 1, xpReward: 150, description: 'Rotate body and board 180 backside.', tutorialUrl: '9z1j9z1j9z1', prerequisiteId: 'skate-ollie' },
  { id: 'skate-nocomply', name: 'No Comply', category: Discipline.SKATE, difficulty: Difficulty.BEGINNER, tier: 1, xpReward: 120, description: 'Step off with front foot, pop with back.', tutorialUrl: '' },
  { id: 'skate-boneless', name: 'Boneless', category: Discipline.SKATE, difficulty: Difficulty.BEGINNER, tier: 1, xpReward: 120, description: 'Grab board, step off, jump back on.', tutorialUrl: '' },

  // TIER 2: CORE TECH
  { id: 'skate-popshuv', name: 'Pop Shuv-it', category: Discipline.SKATE, difficulty: Difficulty.INTERMEDIATE, tier: 2, xpReward: 200, description: 'Shuv-it with a pop.', tutorialUrl: 'Oq9Y3i7_G_E', prerequisiteId: 'skate-shuvit' },
  { id: 'skate-kickflip', name: 'Kickflip', category: Discipline.SKATE, difficulty: Difficulty.INTERMEDIATE, tier: 2, xpReward: 300, description: 'Flip the board towards your heel.', tutorialUrl: 'p35Pj_b8W9U', prerequisiteId: 'skate-ollie' },
  { id: 'skate-heelflip', name: 'Heelflip', category: Discipline.SKATE, difficulty: Difficulty.INTERMEDIATE, tier: 2, xpReward: 300, description: 'Flip the board away from toes.', tutorialUrl: '339k4XEvbxY', prerequisiteId: 'skate-ollie' },
  { id: 'skate-5050', name: '50-50 Grind', category: Discipline.SKATE, difficulty: Difficulty.INTERMEDIATE, tier: 2, xpReward: 350, description: 'Grind both trucks on a ledge.', tutorialUrl: '9z1j9z1j9z1', prerequisiteId: 'skate-ollie' },
  { id: 'skate-boardslide', name: 'Boardslide', category: Discipline.SKATE, difficulty: Difficulty.INTERMEDIATE, tier: 2, xpReward: 300, description: 'Slide the middle of the board on a rail.', tutorialUrl: '', prerequisiteId: 'skate-ollie' },
  { id: 'skate-fakie-ollie', name: 'Fakie Ollie', category: Discipline.SKATE, difficulty: Difficulty.INTERMEDIATE, tier: 2, xpReward: 250, description: 'Ollie while rolling backwards.', tutorialUrl: '', prerequisiteId: 'skate-ollie' },

  // TIER 3: ADVANCED
  { id: 'skate-varial', name: 'Varial Kickflip', category: Discipline.SKATE, difficulty: Difficulty.ADVANCED, tier: 3, xpReward: 450, description: 'Pop Shuv-it mixed with a Kickflip.', tutorialUrl: '', prerequisiteId: 'skate-kickflip' },
  { id: 'skate-treflip', name: 'Tre Flip', category: Discipline.SKATE, difficulty: Difficulty.ADVANCED, tier: 3, xpReward: 500, description: '360 Pop Shuv-it + Kickflip. The holy grail.', tutorialUrl: '', prerequisiteId: 'skate-varial' },
  { id: 'skate-5-0', name: '5-0 Grind', category: Discipline.SKATE, difficulty: Difficulty.ADVANCED, tier: 3, xpReward: 400, description: 'Grind on back truck only.', tutorialUrl: '', prerequisiteId: 'skate-5050' },
  { id: 'skate-nosegrind', name: 'Nose Grind', category: Discipline.SKATE, difficulty: Difficulty.ADVANCED, tier: 3, xpReward: 450, description: 'Grind on front truck only.', tutorialUrl: '', prerequisiteId: 'skate-5050' },
  { id: 'skate-crooked', name: 'Crooked Grind', category: Discipline.SKATE, difficulty: Difficulty.ADVANCED, tier: 3, xpReward: 450, description: 'Grind on front truck, angled.', tutorialUrl: '', prerequisiteId: 'skate-nosegrind' },
  { id: 'skate-bigspin', name: 'Big Spin', category: Discipline.SKATE, difficulty: Difficulty.ADVANCED, tier: 3, xpReward: 400, description: '360 Shuv + Body Varial.', tutorialUrl: '', prerequisiteId: 'skate-popshuv' },
  { id: 'skate-smith', name: 'Smith Grind', category: Discipline.SKATE, difficulty: Difficulty.ADVANCED, tier: 3, xpReward: 500, description: 'Back truck grind, front truck dipped.', tutorialUrl: '', prerequisiteId: 'skate-5-0' },

  // TIER 4: PRO MASTERY
  { id: 'skate-hardflip', name: 'Hardflip', category: Discipline.SKATE, difficulty: Difficulty.PRO, tier: 4, xpReward: 600, description: 'FS Pop Shuv + Kickflip (vertical rotation).', tutorialUrl: '', prerequisiteId: 'skate-kickflip' },
  { id: 'skate-laserflip', name: 'Laser Flip', category: Discipline.SKATE, difficulty: Difficulty.PRO, tier: 4, xpReward: 700, description: '360 Heelflip (Frontside 360 Shuv + Heelflip).', tutorialUrl: '', prerequisiteId: 'skate-heelflip' },
  { id: 'skate-bluntslide', name: 'Bluntslide', category: Discipline.SKATE, difficulty: Difficulty.PRO, tier: 4, xpReward: 650, description: 'Ollie over, land on tail/wheels, slide.', tutorialUrl: '', prerequisiteId: 'skate-boardslide' },
  { id: 'skate-impossible', name: 'Impossible', category: Discipline.SKATE, difficulty: Difficulty.PRO, tier: 4, xpReward: 600, description: 'Wrap board 360 vertical around back foot.', tutorialUrl: '', prerequisiteId: 'skate-treflip' },
  { id: 'skate-feeble', name: 'Feeble Grind', category: Discipline.SKATE, difficulty: Difficulty.PRO, tier: 4, xpReward: 600, description: 'Back truck grind, front truck over rail.', tutorialUrl: '', prerequisiteId: 'skate-smith' },

  // DOWNHILL
  { id: 'dh-tuck', name: 'Speed Tuck', category: Discipline.DOWNHILL, difficulty: Difficulty.BEGINNER, tier: 1, xpReward: 100, description: 'Aerodynamic stance for speed.', tutorialUrl: '6t2j7S7Jp4E' },
  { id: 'dh-footbreak', name: 'Footbrake', category: Discipline.DOWNHILL, difficulty: Difficulty.BEGINNER, tier: 1, xpReward: 100, description: 'Safe stopping at speed.', tutorialUrl: '' },
  { id: 'dh-carve', name: 'Deep Carve', category: Discipline.DOWNHILL, difficulty: Difficulty.BEGINNER, tier: 1, xpReward: 100, description: 'Speed control via turning.', tutorialUrl: '' },
  { id: 'dh-coleman', name: 'Coleman Slide', category: Discipline.DOWNHILL, difficulty: Difficulty.INTERMEDIATE, tier: 2, xpReward: 400, description: 'Heelside glove-down shutdown slide.', tutorialUrl: '6t2j7S7Jp4E', prerequisiteId: 'dh-tuck' },
  { id: 'dh-pushup', name: 'Push-up Slide', category: Discipline.DOWNHILL, difficulty: Difficulty.INTERMEDIATE, tier: 2, xpReward: 400, description: 'Toeside glove-down slide.', tutorialUrl: '', prerequisiteId: 'dh-tuck' },
  { id: 'dh-predrift-heel', name: 'Heel Pre-drift', category: Discipline.DOWNHILL, difficulty: Difficulty.INTERMEDIATE, tier: 2, xpReward: 450, description: 'Cornering slide with hand down.', tutorialUrl: '', prerequisiteId: 'dh-coleman' },
  { id: 'dh-pendulum', name: 'Pendulum', category: Discipline.DOWNHILL, difficulty: Difficulty.INTERMEDIATE, tier: 2, xpReward: 450, description: 'Long glove-down shutdown slide.', tutorialUrl: '', prerequisiteId: 'dh-coleman' },
  { id: 'dh-standie-heel', name: 'Heelside Standie', category: Discipline.DOWNHILL, difficulty: Difficulty.ADVANCED, tier: 3, xpReward: 500, description: 'Stand-up 180 slide.', tutorialUrl: '', prerequisiteId: 'dh-coleman' },
  { id: 'dh-standie-toe', name: 'Toeside Standie', category: Discipline.DOWNHILL, difficulty: Difficulty.ADVANCED, tier: 3, xpReward: 550, description: 'Stand-up toeside check.', tutorialUrl: '', prerequisiteId: 'dh-pushup' },
  { id: 'dh-predrift-toe', name: 'Toe Pre-drift', category: Discipline.DOWNHILL, difficulty: Difficulty.ADVANCED, tier: 3, xpReward: 500, description: 'Cornering toeside with hand down.', tutorialUrl: '', prerequisiteId: 'dh-pushup' },
  { id: 'dh-switch-180', name: 'Switch 180', category: Discipline.DOWNHILL, difficulty: Difficulty.ADVANCED, tier: 3, xpReward: 550, description: 'Sliding 180 into switch stance.', tutorialUrl: '', prerequisiteId: 'dh-standie-heel' },
  { id: 'dh-squat', name: 'Squat Slide', category: Discipline.DOWNHILL, difficulty: Difficulty.PRO, tier: 4, xpReward: 700, description: 'Slide while in a full squat (no hands).', tutorialUrl: '', prerequisiteId: 'dh-standie-heel' },
  { id: 'dh-360', name: '360 Slide', category: Discipline.DOWNHILL, difficulty: Difficulty.PRO, tier: 4, xpReward: 800, description: 'Full rotation stand-up slide at speed.', tutorialUrl: '', prerequisiteId: 'dh-standie-heel' },
  { id: 'dh-pack', name: 'Pack Riding', category: Discipline.DOWNHILL, difficulty: Difficulty.PRO, tier: 4, xpReward: 600, description: 'Close proximity drafting and passing.', tutorialUrl: '', prerequisiteId: 'dh-predrift-heel' },
  { id: 'dh-airbrake', name: 'Air Braking', category: Discipline.DOWNHILL, difficulty: Difficulty.PRO, tier: 4, xpReward: 500, description: 'Using body drag to slow down before corners.', tutorialUrl: '', prerequisiteId: 'dh-tuck' },

  // FREESTYLE
  { id: 'free-railstand', name: 'Rail Stand', category: Discipline.FREESTYLE, difficulty: Difficulty.BEGINNER, tier: 1, xpReward: 150, description: 'Standing on the edge of the board (Primo).', tutorialUrl: '' },
  { id: 'free-pogo', name: 'Pogo', category: Discipline.FREESTYLE, difficulty: Difficulty.BEGINNER, tier: 1, xpReward: 150, description: 'Bouncing on the truck vertically.', tutorialUrl: '' },
  { id: 'free-casper', name: 'Casper Stall', category: Discipline.FREESTYLE, difficulty: Difficulty.BEGINNER, tier: 1, xpReward: 200, description: 'Board upside down, foot under/over.', tutorialUrl: '' },
  { id: 'free-manual', name: 'Manual', category: Discipline.FREESTYLE, difficulty: Difficulty.BEGINNER, tier: 1, xpReward: 100, description: 'Wheelie balance.', tutorialUrl: '' },
  { id: 'free-spacewalk', name: 'Spacewalk', category: Discipline.FREESTYLE, difficulty: Difficulty.INTERMEDIATE, tier: 2, xpReward: 300, description: 'Continuous manual swing.', tutorialUrl: '', prerequisiteId: 'free-manual' },
  { id: 'free-fingerflip', name: 'Fingerflip', category: Discipline.FREESTYLE, difficulty: Difficulty.INTERMEDIATE, tier: 2, xpReward: 250, description: 'Flipping the board with hand.', tutorialUrl: '' },
  { id: 'free-truckstand', name: 'Truck Stand', category: Discipline.FREESTYLE, difficulty: Difficulty.INTERMEDIATE, tier: 2, xpReward: 300, description: 'Balancing on truck and edge.', tutorialUrl: '', prerequisiteId: 'free-pogo' },
  { id: 'free-walkdog', name: 'Walk The Dog', category: Discipline.FREESTYLE, difficulty: Difficulty.INTERMEDIATE, tier: 2, xpReward: 250, description: 'Spinning board around feet while walking.', tutorialUrl: '' },
  { id: 'free-handstand', name: 'Handstand', category: Discipline.FREESTYLE, difficulty: Difficulty.ADVANCED, tier: 3, xpReward: 500, description: 'Handstand on the moving board.', tutorialUrl: '' },
  { id: 'free-coconut', name: 'Coconut Wheel', category: Discipline.FREESTYLE, difficulty: Difficulty.ADVANCED, tier: 3, xpReward: 600, description: 'Rolling on the side edge (Primo slide).', tutorialUrl: '', prerequisiteId: 'free-railstand' },
  { id: 'free-anticasper', name: 'Anti-Casper', category: Discipline.FREESTYLE, difficulty: Difficulty.ADVANCED, tier: 3, xpReward: 550, description: 'Casper stall on the nose.', tutorialUrl: '', prerequisiteId: 'free-casper' },
  { id: 'free-impossible', name: 'Impossible', category: Discipline.FREESTYLE, difficulty: Difficulty.ADVANCED, tier: 3, xpReward: 500, description: 'Vertical board wrap around foot.', tutorialUrl: '' },
  { id: 'free-gazelle', name: '720 Gazelle', category: Discipline.FREESTYLE, difficulty: Difficulty.PRO, tier: 4, xpReward: 800, description: '540 Body varial + 720 board spin.', tutorialUrl: '' },
  { id: 'free-carousel', name: 'Carousel', category: Discipline.FREESTYLE, difficulty: Difficulty.PRO, tier: 4, xpReward: 750, description: 'Truck-to-truck transfer spin.', tutorialUrl: '', prerequisiteId: 'free-truckstand' },
  { id: 'free-rusty', name: 'Rusty Slide', category: Discipline.FREESTYLE, difficulty: Difficulty.PRO, tier: 4, xpReward: 700, description: 'High speed powerslide in manual.', tutorialUrl: '', prerequisiteId: 'free-spacewalk' },
];

export const COLLECTIBLES_DATABASE: Collectible[] = [
  { id: 'deck_first_push', name: 'First Push', type: CollectibleType.DECK, rarity: Rarity.COMMON, imageUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=deck1', description: 'Your first set of wheels.' },
  { id: 'sticker_7_day', name: 'Week Warrior', type: CollectibleType.STICKER, rarity: Rarity.RARE, imageUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=sticker7', description: '7 day streak bonus.' }
];

export const MENTOR_BADGE_META: Record<string, { label: string, color: string }> = {
  [MentorBadge.CERTIFIED]: { label: 'SPOTS Certified', color: 'bg-indigo-500' },
  [MentorBadge.EXPERT]: { label: 'Expert Faculty', color: 'bg-amber-500' }
};
